apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  generation: 11
  labels:
    app: nexus
  name: nexus
  namespace: ${NAMESPACE}
  selfLink: /apis/apps.openshift.io/v1/namespaces/${NAMESPACE}/deploymentconfigs/nexus
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: nexus
    deploymentconfig: nexus
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: nexus
        deploymentconfig: nexus
    spec:
      containers:
        - image: >-
            sonatype/nexus@sha256:cd99a0982eb74c99cc15006a5b97b64a1308b5055d25344e48ee60bbda587cb0
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nexus
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /nexus/content/groups/public
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /sonatype-work
              name: nexus-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nexus-volume-1
          persistentVolumeClaim:
            claimName: nexus-pv
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nexus
        from:
          kind: ImageStreamTag
          name: 'nexus:latest'
          namespace: ${NAMESPACE}
        lastTriggeredImage: >-
          sonatype/nexus@sha256:cd99a0982eb74c99cc15006a5b97b64a1308b5055d25344e48ee60bbda587cb0
      type: ImageChange
