apiVersion: v1
kind: ImageStream
metadata:          
  name: blob-replicator-build  
spec: {}
status:
  dockerImageRepository: ""    

---

apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: blob-replicator-build
spec:
  triggers:
  - type: ConfigChange
  source:
    git:
      uri: https://github.com/tiry/nuxeo-blob-replicator
      ref: master
    type: Git    
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'openshift/wildfly-101-centos7'
      incremental: true      
  output:
    to:
      kind: ImageStreamTag
      name: blob-replicator-build:latest
