apiVersion: v1
kind: BuildConfig
metadata:
  name: nuxeo-app-assemble
  labels:
    app: nuxeo
    component: assembly
spec:
  source:
    dockerfile: |-
      FROM nuxeo:9.3
      USER root
      COPY build /build
    images:
      - from:
          kind: ImageStreamTag
          name: nuxeo-app-build:latest
        paths:
          - destinationDir: .
            sourcePath: /build
    secrets:
      - destinationDir: ./
        secret:
          name: nuxeo-connect
    type: Dockerfile
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: nuxeo:9.3
    type: Docker
  triggers:
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: nuxeo-app-build:latest
  output:
    to:
      kind: ImageStreamTag
      name: 'nuxeo-nuxeo:intermediate'
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: nuxeo-app-assemble2
  labels:
    app: nuxeo
    component: assembly
spec:
  source:
    dockerfile: |-
      FROM nuxeo:9.3
      USER root
      COPY blob-replicator-build/* /build/artifacts      
    images:
      - from:
          kind: ImageStreamTag
          name: blob-replicator-build:latest
        paths:
          - destinationDir: blob-replicator-build
            sourcePath: /wildfly/standalone/deployments
    secrets:
      - destinationDir: ./
        secret:
          name: nuxeo-connect
    type: Dockerfile
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: nuxeo-nuxeo:intermediate
    type: Docker  
  output:
    to:
      kind: ImageStreamTag
      name: 'nuxeo-nuxeo:latest'
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: nuxeo-app-assemble3
  labels:
    app: nuxeo
    component: assembly
spec:
  source:
    dockerfile: |-
      FROM nuxeo:9.3
      USER root
      COPY es-connector-build/* /build/artifacts      
      COPY ./connect.properties /opt/nuxeo/connect/connect.properties
      USER 1000
      RUN /build/install.sh
      # Clean credential after using it
      USER root
      RUN rm -f /opt/nuxeo/connect/connect.properties
      USER 1000
    images:
      - from:
          kind: ImageStreamTag
          name: es-connector-build:latest
        paths:
          - destinationDir: es-connector-build
            sourcePath: /wildfly/standalone/deployments
    secrets:
      - destinationDir: ./
        secret:
          name: nuxeo-connect

    
    type: Dockerfile
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: nuxeo-nuxeo:latest
    type: Docker  
  output:
    to:
      kind: ImageStreamTag
      name: 'nuxeo-nuxeo:latest'

