apiVersion: v1
kind: ConfigMap
metadata:
  name: mirrormaker-config
  labels:    
    app: mirroring
    component: mirrormaker

data:
  consumer.properties: |-
    bootstrap.servers=10.20.5.4:32094,10.20.6.43:32094,10.20.4.22:32094
    group.id=drp-MirrorMaker-group
    exclude.internal.topics=true      
    client.id=mirror_maker_consumer
  producer.properties: |-
    bootstrap.servers=nuxeo-backings-kafka-0.nuxeo-backings-kafka:9092,nuxeo-backings-kafka-1.nuxeo-backings-kafka:9092,nuxeo-backings-kafka-2.nuxeo-backings-kafka:9092
    acks=1
    batch.size=1
    client.id=mirror_maker_producer    
  log4j.properties: |-
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

    # Suppress connection log messages, three lines per livenessProbe execution
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxnFactory=WARN
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxn=WARN

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mirrormaker
  labels:
    app: mirroring
    component: mirrormaker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mirroring
        component: mirrormaker
    spec:      
      containers:
      - name: kafka-mirror
        image: solsson/kafka:0.11.0.1
        imagePullPolicy: Always
        env:
          - name: KAFKA_LOG4J_OPTS
            value: -Dlog4j.configuration=file:/etc/kafka/log4j.properties
        ports:
          - containerPort: 9092
        command:
          - ./bin/kafka-mirror-maker.sh
          - --consumer.config
          -   /etc/kafka/consumer.properties
          - --producer.config
          -   /etc/kafka/producer.properties
          - --whitelist=".*"          
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /etc/kafka          
        - name: logs
          mountPath: /opt/kafka/logs
      volumes:
      - name: config
        configMap:
          name: mirrormaker-config
      - name: logs
        emptyDir: {}

