apiVersion: v1
kind: ImageStream
metadata:          
  name: mongodb-connect-build 
spec: {}
status:
  dockerImageRepository: ""    

---
apiVersion: v1
kind: ImageStream
metadata:          
  name: mongodb-connect  
spec: {}
status:
  dockerImageRepository: ""    

---

apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    component: mongodb-connect
  name: mongodb-connect-build
spec:
  triggers:
  - type: ConfigChange
  source:
    git:
      uri: https://github.com/dmetzler/kafka-connect-mongodb
      ref: master
    type: Git    
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'openshift/wildfly-101-centos7'
      incremental: true      
  output:
    to:
      kind: ImageStreamTag
      name: mongodb-connect-build:latest

---

apiVersion: v1
kind: BuildConfig
metadata:
  name: mongodb-connect-assemble
  labels:
    component: mongodb-connect
spec:
  source:
    dockerfile: |-
      FROM solsson/kafka:0.11.0.1
      RUN mkdir /plugins
      COPY deployments/*with-dependencies* /plugins/
    images:
      - from:
          kind: ImageStreamTag
          name: mongodb-connect-build:latest
        paths:
          - destinationDir: .
            sourcePath: /wildfly/standalone/deployments/
    type: Dockerfile
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: solsson/kafka:0.11.0.1
    type: Docker
  triggers:
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: mongodb-connect-build:latest
  output:
    to:
      kind: ImageStreamTag
      name: mongodb-connect:latest


