apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  generation: 7
  labels:
    template: jenkins-ephemeral-template
  name: jenkins
  namespace: ${NAMESPACE}
  selfLink: /apis/apps.openshift.io/v1/namespaces/${NAMESPACE}/deploymentconfigs/jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jenkins
    spec:
      containers:
        - env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: 'true'
            - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
              value: 'true'
            - name: KUBERNETES_MASTER
              value: 'https://kubernetes.default:443'
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: 'true'
            - name: JENKINS_SERVICE_NAME
              value: jenkins
            - name: JNLP_SERVICE_NAME
              value: jenkins-jnlp
            - name: INSTALL_PLUGINS
              value: >-
                maven-plugin, pipeline-maven, file-operations,
                apache-httpcomponents-client-4-api, junit-attachments, tasks
          image: >-
            docker.io/openshift/jenkins-2-centos7@sha256:59b9b12acf8e048186fac8c9fce2759a4d7883fb1b1be33a778d236b573f720d
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: jenkins-data
            - mountPath: /var/lib/jenkins/configuration
              name: volume-osv0d
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: jenkins-data
        - configMap:
            defaultMode: 420
            items:
              - key: MAVEN_SETTINGS
                path: settings.xml
            name: maven-settings
          name: volume-osv0d
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
        from:
          kind: ImageStreamTag
          name: 'jenkins:latest'
          namespace: openshift
        lastTriggeredImage: >-
          docker.io/openshift/jenkins-2-centos7@sha256:59b9b12acf8e048186fac8c9fce2759a4d7883fb1b1be33a778d236b573f720d
      type: ImageChange
    - type: ConfigChange
