apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ${APPLICATION_NAME}
  name: qa-app-build
  namespace: ${NAMESPACE}
  selfLink: /apis/build.openshift.io/v1/namespaces/${NAMESPACE}/buildconfigs/qa-app-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'qa-app-image:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary:
      asFile: source
    dockerfile: >-
      # Start from a Nuxeo base image

      FROM qa-base-image:latest

      # Set up the /build folder with the install script, the marketplace
      package and the studio credentials

      USER root

      RUN mkdir -p /build/marketplace

      COPY install.sh /build

      COPY marketplace.zip /build/marketplace

      RUN chmod -R 777 /build

      COPY ./connect.properties /opt/nuxeo/connect/connect.properties

      RUN chmod 777 /opt/nuxeo/connect/connect.properties

      # Run the image build script

      USER 1000

      RUN /build/install.sh

      # Clean the server

      USER root

      RUN rm -f /opt/nuxeo/connect/connect.properties && \
          chgrp -fR 0 /opt/nuxeo/server/ && \
          chmod -fR g+rwX /opt/nuxeo/server/

      USER 1000
    secrets:
      - secret:
          name: connect-credentials
    type: Binary
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: 'qa-base-image:latest'
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers: []
