apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  labels:
    app: ${APPLICATION_NAME}
  name: qa-app-image
  namespace: ${NAMESPACE}
  selfLink: /apis/image.openshift.io/v1/namespaces/${NAMESPACE}/imagestreams/qa-app-image
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 'docker-registry.default.svc:5000/${NAMESPACE}/qa-app-image'
