apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: nexus
  name: nexus
  namespace: ${NAMESPACE}
  selfLink: /api/v1/namespaces/${NAMESPACE}/services/nexus
spec:
  clusterIP: 172.30.193.15
  ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus
    deploymentconfig: nexus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
