apiVersion: v1
kind: ImageStream
metadata:          
  name: elasticsearch-searchguard    
spec: {}
---  
apiVersion: v1
kind: BuildConfig
metadata:
  name: elasticsearch-searchguard-build    
spec:
  source:
    dockerfile: |-
      FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.9

      RUN echo "===> Installing search-guard..." \
        && /usr/share/elasticsearch/bin/elasticsearch-plugin install -b "com.floragunn:search-guard-5:5.6.5-18"

    type: Dockerfile
  strategy:
    dockerStrategy:
      forcePull: true
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'elasticsearch-searchguard:latest'
  successfulBuildsHistoryLimit: 2 
  failedBuildsHistoryLimit: 2 
