apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - port: 8080
    name: transport
  clusterIP: None
  selector:
    app: nuxeo-openshift
